### ISSUE TITLE
about the interaction rules

### ISSUE THREAD

**Issue by DavidGRX** [HackerPoet/Particle-Life#2]
Dear HackerPoet:
 I would like to know where can I find a text description of the interaction rules (formulas) among particles. 

All the best and thanks for sharing

David

**Comment by yjmantilla** [comment]
There is no text description yet. One could analyze the code, especially particles.h and universe.cpp. In particles.h you will find the ontology of the particles and in universe.cpp you will find the actual formulas being used, particularly in the method Universe:Step().

From what I understood from a quick reading of the code it seems like he makes an square matrix with the values of attraction strength between the type with itself and with every other type. 

Also there are 2 more matrices that seem to describe spatial range limits for the attraction to occur and how does it occur: 

If the particles are away less than Rmax but greater than Rmin then they will interact in a canonical way. Which is a value of the matrix multiplied by an scaling factor. Apparently there is a boolean called m_flat_force that omits this scaling factor.

If the particles are away less than Rmin but greater than 0.01 they interact with some kind of transformation over the canonical interaction.

In both cases he outputs value "f" which seems to be the force of attraction. This force modifies the kinematics (velocity and position) of the receiving particle as a result of the effect of the emitter particle, so to speak.

If the particles are away more than Rmax or are too close (apparently less than 0.01) they wont interact.

And so arise the interaction rules. I could be wrong so check the code by yourself, I just did a quick reading of it.
